%In this matlab GDS file we will be creating an accelerometer in GDS
%modeling the accelerometer proposed in this paper which we will link
%below....
%
% "Design and FEM Analysis of Navigation Grade Low
%Noise and High Sensitivity Capacitive MEMS
%Accelerometer based on SOIMUMPs Process
%Constraints" (The paper Name)
%

%let's start by creating our top level gds library and structure objects...
clear all

%create our toplevel structure
gd = gds_structure('Main Accelerometer Structure');

%Now let's create the main body of the accelerometer

%creates a box of 3000um * 2000um consistent with dimensions in the paper
proof_mass_center = proof_mass_center(3,2,0,0,false);
%now we add the proof mass center inside the gds_structure
gd(end+1) = gds_element('boundary', 'xy',proof_mass_center, 'layer',0);



%Now let's write the code which will make our stator combs
% we use a function which generates the stator combs....
gd = stator_combs( ...
    0,...
    3,...
    3,...
    2,...
    0.1,...
    0.5,...
    10,...
    0.01,...
    gd,...
    true);



%Now this portion of the code will be dedicated to generating the rotor
%combs, we call the rotor_comb generating function
gd = rotor_combs( ...
    0,...
    0,...
    3,...
    2,...
    4,...
    1,...
    0.1,...
    gd,...
    0.1,...
    true);

%now let's try generating the cage....
generate_cage( ...
    gd,...
    true);



%create our library to hold the accelerometer structures
glib = gds_library('accelerometer', 'uunit','1e-6', 'dbunit','1e-9', gd);
glib = add_struct(glib, out);


%Now we write the file to complete everything....
write_gds_library(glib, '!accelerometer.gds');


