#!/bin/sh

export CFLAGS='-O3'

cd Basic/gdsio
mkoctfile --mex gdsii_excess64enc.c
mkoctfile --mex gdsii_excess64dec.c
rm *.o

cd ../@gds_element/private
mkoctfile --mex poly_iscwmex.c
rm *.o

cd ../../../Structures/private
mkoctfile --mex datamatrixmex.c
rm *.o

cd ../../Boolean/clipper
mkoctfile --mex poly_boolmex.cpp clipper.cpp
rm *.o

cd ../..


